<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>YetAnotherOneCLauncher.App</RootNamespace>
    <AssemblyName>YetAnotherOneCLauncher</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="YetAnotherOneCLauncher.App.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YetAnotherOneCLauncher.Core\YetAnotherOneCLauncher.Core.csproj" />
    <ProjectReference Include="..\YetAnotherOneCLauncher.Platform\YetAnotherOneCLauncher.Platform.csproj" />
  </ItemGroup>

</Project>
